/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.testing;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

import com.nt.xyz.Calculation;

public class JunitTest {
	private Calculation cal=new Calculation();
	@Test  
    public void testFindMax(){  
        //assertEquals(4,cal.findMax(new int[]{1,3,4,2}));  
       // assertEquals(-1,cal.findMax(new int[]{-12,-1,-3,-4,-2}));
        
        //assertTrue(cal.findVal(140));
       // assertFalse(cal.findVal(40));
        
        
    }  
	
	@Test
	public void test() {
		//assertEquals(13, cal.add(5, 8));
		//assertNull(cal);
		assertNotNull(cal);
	}
}
